Reran uwuification with increased percentages if text unchanged
letsbuilda/imsosorry pull request #38
Opened 2023-08-10 03:17 UTC by SomeHybrid

The current uwuification function has a chance of some special text such as "it's just syntax" being unaffected by the uwuification. This change will rerun the uwuification function with increase chance parameters to ensure at least some uwuification for all texts.

Examples:
Before the uwuification change:
![image](https://github.com/letsbuilda/imsosorry/assets/91648368/df2d62b8-0a84-4065-832c-b8db4fe4ff00)
![image](https://github.com/letsbuilda/imsosorry/assets/91648368/afe24fd6-210e-4984-b077-e2635a5813e3)

After the uwuification change:
```py
>>> imsosorry.uwuify("It's just syntax")
"it's j-just syntax"```

```py
>>> imsosorry.uwuify("sowwy")
'sowwy~'```

2023-08-10 03:28 UTC, thatbirdguythatuknownot commented
i'm gonna add this to my C extension too

2023-08-10 03:31 UTC, Robin5605 requested changes

2023-08-10 03:31 UTC, Robin5605 commented on src/imsosorry/uwuification.py
> +    return text
```suggestion
    text = tildify(text, tilde_strength)

    if text == original_text:
        text = uwuify(
            text,
            stutter_strength=stutter_strength + 0.225,
            emoji_strength=emoji_strength + 0.075,
            tilde_strength=tilde_strength + 0.175,
        )

    return text
```
Since this is a recursive function, all we need is an if statement rather than a while statement

2023-08-10 03:46 UTC, Robin5605 approved these changes
LGTM :shipit:

2023-08-10 03:51 UTC, thatbirdguythatuknownot commented
wouldn't this break if, for example, there's an empty string?

2023-08-10 03:52 UTC, Robin5605 commented
> wouldn't this break if, for example, there's an empty string?

Probably, though that's an easy enough fix, we can simply add something like:
```py
if not text:
    return text
```
To simply return the empty string before any processing is done

2023-08-10 03:54 UTC, thatbirdguythatuknownot commented
> > wouldn't this break if, for example, there's an empty string?
> 
> Probably, though that's an easy enough fix, we can simply add something like:
> 
> ```python
> if not text:
>     return text
> ```
> 
> To simply return the empty string before any processing is done

seems like it just returns a tilde... weird, but alright

2023-08-10 04:52 UTC, SomeHybrid commented
An empty string and `-` seem to also just get returned in this

2023-08-10 05:07 UTC, thatbirdguythatuknownot commented
> An empty string and `-` seem to also just get returned in this

```py
>>> from uwuifier import uwuify
>>> uwuify("-")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 19, in uwuify
  File "<stdin>", line 19, in uwuify
  File "<stdin>", line 19, in uwuify
  [Previous line repeated 991 more times]
  File "<stdin>", line 13, in uwuify
  File "<stdin>", line 3, in nyaify
  File "C:\Program Files\Python311\Lib\re\__init__.py", line 317, in _subx
    template = _compile_repl(template, pattern)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in comparison
```
Not sure what you're testing there.

2023-08-10 05:25 UTC, SomeHybrid commented
> > An empty string and `-` seem to also just get returned in this
> 
> ```python
> >>> from uwuifier import uwuify
> >>> uwuify("-")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "<stdin>", line 19, in uwuify
>   File "<stdin>", line 19, in uwuify
>   File "<stdin>", line 19, in uwuify
>   [Previous line repeated 991 more times]
>   File "<stdin>", line 13, in uwuify
>   File "<stdin>", line 3, in nyaify
>   File "C:\Program Files\Python311\Lib\re\__init__.py", line 317, in _subx
>     template = _compile_repl(template, pattern)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RecursionError: maximum recursion depth exceeded in comparison
> ```
> 
> Not sure what you're testing there.
```py
>>> imsosorry.uwuify("-")
'-'
```

might be just you

2023-08-10 05:37 UTC, thatbirdguythatuknownot commented
> might be just you

doesn't make sense why `-` shouldn't fail with the new changes
- nothing changed in `word_replace()`
- nothing changed in `nyaify()`
- nothing changed in `char_replace()`
- nothing changed in `stutter()`
- nothing changed in `emoji()`
- nothing changed in `tildify()`
- `"-" == "-"`, so recurse

2023-08-11 03:12 UTC, SomeHybrid commented
Should I just add `if text == original_text and list(string.ascii_letters) in text:`?

2023-09-16 10:04 UTC, shenanigansd requested changes
I don't see any benefit to splitting the main function into two different functions.
Lets just keep it to one function.

2023-09-16 10:04 UTC, shenanigansd commented on src/imsosorry/uwuification.py
> +    return text
We can use `isalpha` to exit early for invalid cases.
```suggestion
    if not text.isalpha():
        return text


    return _uwuify(
        text,
        stutter_strength=stutter_strength,
        emoji_strength=emoji_strength,
        tilde_strength=tilde_strength,
    )
```

2023-09-16 10:04 UTC, shenanigansd commented on src/imsosorry/uwuification.py
> +import string
For the below, this is no longer needed
```suggestion
```

2023-09-16 10:16 UTC, SomeHybrid commented
wait a sec don't merge yet i still gotta write tests

2023-09-16 10:16 UTC, SomeHybrid commented
and that

2023-09-17 13:04 UTC, shenanigansd approved these changes

2023-09-17 13:05 UTC, merged